### ISSUE TITLE
cannot fix redis password

### ISSUE THREAD

**Issue by jraverdy-orange** [pivotal-cf/cf-redis-release#58]
Hello
I would like to fix the redis auth password and manage it in credhub
Unfortunately even if i set it in my deployment by adding the following opsfile

```yaml
- type: replace
  path: /properties/redis/security?/require_pass
  value: ((redis_password))

- type: replace
  path: /variables?/name=redis_password?
  value: 
    name: redis_password
    type: password
```

the provided password is well filled in `/var/vcap/jobs/dedicated-node/config/redis.conf`

```yaml
...
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
#

requirepass 1OujjY5MctbW9OZkfuT61rawh9Icxg
```

but it is overwritten with an uuid in `/var/vcap/store/redis/redis.conf`, which is the configuration file used by redis instance

```yaml
aof-rewrite-incremental-fsync yes
requirepass b3c18089-ca3e-4c60-8f87-c42f27627253
```

Is there anything I missed ?
